M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu23.10.1} date 2024-10-17T21:53:55-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-17T21:53:55-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu23.10.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
%
G90
G05
T1
X5.2341Y-3.5435
X5.5096Y-3.5435
M30
